### ISSUE TITLE
Unable to complete build.sh on CentOs with gfortran 4.4.7

### ISSUE THREAD

**Issue by pirpyn** [jacobwilliams/slsqp#3]
Hi, first thanks for sharing your code.

Running `build.sh` gives the following error : 

```
Compiling src/slsqp_kinds.f90 serially
src/slsqp_kinds.f90:10.44:

    use, intrinsic :: iso_fortran_env, only: real64
                                            1
Error: Symbol 'real64' referenced at (1) does not exist in intrinsic module ISO_FORTRAN_ENV
```
Which version of gfortran is required  ? I have 4.4.7, cannot upgrade : company computer.

Full output: [build.log](https://github.com/jacobwilliams/slsqp/files/1883338/build.log)

**Comment by jacobwilliams** [comment]
It looks like this particular feature (`real64`) was added to gfortran in [4.5](https://gcc.gnu.org/wiki/GFortran/News#gfortran_4.5). Probably you need to use one even newer (6 or 7). Older releases were very incomplete and buggy for modern Fortran features.
