### ISSUE TITLE
Constraints violation

### ISSUE THREAD

**Issue by Netphilou31** [jacobwilliams/slsqp#34]
Hi,
Not sure exactly about that but it seems that the test on the constraints violation made in subroutine check_convergence in module slsqp_core is written the wrong way. Indeed, the test is:
```fortran
    if (h3 < acc) then
        mode = not_converged
    else
```
whereas, in my point of view, it should be the reverse:
```fortran
    if (h3 > acc) then
        mode = not_converged
    else
```
I have an optimization problem which stops because the function change is less than the tolerance, but the constraints are not satisfied whereas when the test is reversed, the calculation continues and stops correctly with the right solution.
Any comments?
Best regards,

**Comment by Netphilou31** [comment]
Hi,
After doing some google search, I was able to download a previous version of the SLSQPB routine where the code was: 
```fortran
C   CHECK CONVERGENCE

  240 H3 = ZERO
      DO 250 J=1,M
         IF (J.LE.MEQ) THEN
             H1 = C(J)
         ELSE
             H1 = ZERO
         ENDIF
         H3 = H3 + MAX(-C(J),H1)
  250 CONTINUE
      IF ((ABS(F-F0).LT.ACC .OR. DNRM2(N,S,1).LT.ACC) .AND. H3.LT.ACC)
     *   THEN
            MODE = 0
         ELSE
            MODE = -1
         ENDIF
      GO TO 330

C   CHECK relaxed CONVERGENCE in case of positive directional derivative

  255 CONTINUE
      IF ((ABS(F-F0).LT.TOL .OR. DNRM2(N,S,1).LT.TOL) .AND. H3.LT.TOL)
     *   THEN
            MODE = 0
         ELSE
            MODE = 8
         ENDIF
      GO TO 330
``` 
As you can see the test on H3 is ```H3.LT.ACC``` or ```H3.LT.TOL``` and is added with a AND condition in the other convergence tests, so I guess that there was an error in the code rewrite.
Best regards,

**Comment by jacobwilliams** [comment]
Thanks! So, I guess it should be:

```fortran
    if (h3 >= acc) then
        mode = not_converged
    else
```

to be consistent with the original code.

**Comment by Netphilou31** [comment]
Yes, I agree with the change.
Thanks.
