### ISSUE TITLE
Question : citing slsqp in a phd

### ISSUE THREAD

**Issue by pirpyn** [jacobwilliams/slsqp#5]
I used your code in a part of my phd (not finished). How should I cite it in poster/report?

**Comment by jacobwilliams** [comment]
Cool! You could just cite the GitHub page. Something like this:
* J. Williams, "Modern Fortran Edition of the SLSQP Optimizer", Version 1.0.2, 28 Mar 2018, https://github.com/jacobwilliams/slsqp

I would be interested in seeing your results when it is finished!
